### ISSUE TITLE
Broken quote in multi-post content

### ISSUE THREAD

**Issue by amadanmath** [Tinywave/polarbytebot#1]
If content is too long, it is broken into multiple posts in `prepare_comment`. However, the first line of the next post will not be quoted; and the break location can be not nice. ([Example](https://www.reddit.com/r/Guildwars2/comments/3nrn28/after_3_betas_thoughts_on_the_tempest_in_new_pve/cvqn611?context=1#siteTable_t1_cvqn5v9))

A trivial way to solve the first is to allow for the quote character

    _current_content = _content[:10000 - len('\n\n--- continued below ---') - len(cfg_file['reddit']['signature'] - 1)]

then prepend it to the continued content:

    _content = '>' + _content[len(_current_content):]

but a nicer solution would only use that as a fallback; before going that route, it would be awesome to look for the last index of `'\n>'` inside `_current_content` and cut it off there, so that broken paragraphs are also avoided.

**Comment by Tinywave** [comment]
Partly already implemeneted in `polarbytebot_alpha.py`, will aim to implemented your second suggestion.

**Comment by Tinywave** [comment]
Implemented cut-off on '\n' in polarbytebot_alpha.py
